---
version: '2'
services:
  fleet-captain:
    build:
      context: .
    working_dir: /usr/src/app
    environment:
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_DEFAULT_REGION
    volumes:
      - .:/usr/src/app
      - ./logs:/usr/src/app/logs/

